name: sezon_app
description: A shop app app , used in this project getX state management and firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter_svg: ^2.0.7
  get: ^4.6.5
  image_picker: ^1.0.1
  pinput: ^2.2.31
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  get_it: ^7.6.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700

