import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'login': 'Login',
          'userName': 'User Name',
          'name': 'ahed eid',
          'password': 'password',
          'forget_your_password': 'you forget your password?',
          'don\'t_have_account': 'you don\'t have an account ',
          'new_account': 'newAccount',
          'this_field_required': 'This field is required',
          'valid_email': 'Enter valid email',
          'password_grater_than_8': 'enter password grater than 8 character',
          'valid_phone': 'enter valid phone number, start +972 or +970',
          'valid_name': 'enter valid name',
          'just_number': 'enter just number',
          'create_new_account': 'create new account',
          'phone_number': 'phone number',
          'password_confirmation': 'password confirmation',
          'register_account': 'register',
          'have_account': 'have an account ',
          'verification_code': 'verification code',
          'otp_message': 'we send verification code for this phone number',
          'send': 'send',
          'home': 'home',
          'category': 'category',
          'orders': 'orders',
          'favorite': 'favorite',
          'search_world_here': 'Search world here',
          'products':'products',
          'Product_details' :'Product details',
          'related_products' :'Related Products',
          'info' :'Info',
          'this_product_already_added_to_the_favorites' :'This product already added to the favorites',
          'add_to_favorites' :'Add to favorites',
          'buy_now' :'Buy now',
          'handmade_colorful_ceramics' :'Handmade colorful ceramics',
          'this_text_is_an_example_of_text' :'This text is an example of text that can be replaced by generating this text from the Arabic text generator...',
       'requests_in_progress': 'Requests in progress',
       'requests_received': 'Requests received',
       'complete_your_purchase': 'Complete your purchase',
       'add_address': 'Add address',
       'choose_a_payment_method': 'Choose a payment method',
       'add_product_specifications': 'Add product specifications',
       'confirmation': 'Confirmation',
       'add_a_new_address': 'Add a new address',
       'the_UAE': 'The UAE',
       'country': 'Country',
       'save': 'Save',
       'postal_code': 'Postal code',
       'street': 'Street',
       'Street_house_residential_unit': 'Street, house, residential unit...',
       'city': 'City',
       'sheikh_zayed': 'sheikh Zayed',
       'region': 'Region',
       'region_province_state': 'Region, province, state...',
       'next': 'Next',
       'visa_card': 'Visa card',
       'stripe_card': 'stripe card',
       'choose_payment_method': 'Choose payment method',
       'card_data': 'Card data',
       'product_name': 'product name',
       'example_handmade_colorful_ceramics': 'Example: Handmade colorful ceramics',
       'quantity': 'Quantity',
       'example_5_pieces': 'Example: 5 pieces',
       'product_color': 'Product color',
       'the_size': 'the size',
       'example_xxl': 'Example: xxl',
       'profile': 'Profile',
       'edit_profile': 'Edit profile',
       'language': 'Change Language',
       'logout': 'Logout',
        },
    //------------------------- arabic ---------------------------
        'ar': {
          'login': 'تسجيل الدخول',
          'userName': 'اسم المستخدم',
          'name': 'عاهد عيد',
          'password': 'كلمة المرور',
          'forget_your_password': 'هل نسيت كلمة المرور؟',
          'don\'t_have_account': 'ليس لديك حساب؟ ',
          'new_account': 'حساب جديد',
          'this_field_required': 'هذا الحقل مطلوب',
          'valid_email': 'ادخل ايميل صالح',
          'password_grater_than_8': 'ادخل كلمة مرور اكبر من 8 احرف',
          'valid_phone': 'ادخل رقم هاتف صالح يبدأ ب +972 او +970',
          'valid_name': 'ادخل اسم صحيح ',
          'just_number': 'مسموح ادخال ارقام فقط',
          'create_new_account': 'إنشاء حساب جديد',
          'phone_number': 'رقم الهاتف',
          'password_confirmation': 'تأكيد كلمة المرور',
          'register_account': 'تسجيل حساب',
          'have_account': 'هل لديك حساب؟ ',
          'verification_code': 'رمز التحقق',
          'otp_message': 'لقد قمنا بارسال رمز التحقق إلى هذا \nالرقم ',
          'send': 'أرسل',
          'home': 'الرئيسية',
          'category': 'الفئات',
          'orders': 'طلباتي',
          'favorite': 'المفضلة',
          'search_world_here': 'كلمة البحث هنا',
          'products':'المنتجات',
          'Product_details': 'تفاصيل المنتج',
          'related_products': 'منتجات ذات صلة',
          'info': 'معلومات',
          'this_product_already_added_to_the_favorites': 'تمت إضافة هذا المنتج بالفعل إلى المفضلة',
          'add_to_favorites': 'إضافة إلى المفضلة',
          'buy_now': 'شراء الان',
          'handmade_colorful_ceramics': 'خزف ملون صنع يدوي',
          'this_text_is_an_example_of_text': 'هذا النص هو مثال لنص يمكن أن يستبدل \nتوليد هذا النص من مولد النص العربى...',
          'requests_in_progress':'طلبات قيد التنفيذ',
          'requests_received':'طلبات مستلمة',
          'complete_your_purchase':'إتمام عملية الشراء',
          'add_address':'إضافة عنوان',
          'choose_a_payment_method':'اختر طريقة دفع',
          'add_product_specifications':'اضافة مواصفات المنتج',
          'confirmation':'تأكيد الطلب',
          'add_a_new_address':'إضافة عنوان جديد',
          'the_UAE':'الامارات',
          'country':'الدولة',
          'save':'حفظ',
         'postal_code':'الرمز البريدي',
         'street':'الشارع',
         'Street_house_residential_unit':'الشارع، المنزل، الوحدة السكنية...',
         'city':'المدينة',
         'sheikh_zayed':'الشيخ زايد',
         'region': 'المنطقة',
         'region_province_state': 'المنطقة، محافظة، ولاية...',
         'next': 'التالي',
         'visa_card': 'بطاقة الفيزا',
         'stripe_card': 'بطاقة stripe',
         'choose_payment_method': 'اختر طريقة الدفع',
         'card_data': 'بيانات البطاقة',
         'product_name': 'اسم المنتج',
         'example_handmade_colorful_ceramics': 'مثال: خزف ملون صنع يدوي',
          'quantity':'الكمية',
          'example_5_pieces':'مثال: 5 قطع',
          'product_color':'لون المنتج',
          'example_black':'مثال: الأسود',
          'the_size':'الحجم',
          'example_xxl':'مثال: xxl',
          'profile':'الملف الشخصي',
          'edit_profile':'تعديل الملف الشخصي',
          'language':'تغير اللغة',
          'logout':'تسجيل الخروج',

        }
      };
}
